### ISSUE TITLE
Make link via AceDRG fails

### ISSUE THREAD

**Issue by olibclarke** [pemsley/coot#188]
Hi @pemsley,

I attempted to make a link using AceDRG in Coot 0.9.8.95, using the tutorial data as described here: 

https://pemsley.github.io/coot/blog/2020/06/30/make-a-link.html

Am I right in thinking this is still the preferred way to add covalent links to ligands (as opposed to "Make link" or JLigand?

It failed with an error:

<img width="639" alt="image" src="https://github.com/user-attachments/assets/ebbbd8e7-0a9d-41df-ad79-01431d79c353" />

Checking the terminal:
```bash
click-1: (1 0 "B" 258 "" " NZ " "")
click-2: (1 0 "B" 601 "" " C4A" "")
cif-fn-1: "/Applications/CCP4/ccp4-9/lib/data/monomers/l/LYS.cif"
cif-fn-2: "/Applications/CCP4/ccp4-9/lib/data/monomers/p/PLP.cif"
ns:       ("PLP")
LINK string: "LINK: RES-NAME-1 LYS ATOM-NAME-1  NZ  RES-NAME-2 PLP ATOM-NAME-2  C4A BOND-TYPE DOUBLE FILE-2 /Applications/CCP4/ccp4-9/lib/data/monomers/p/PLP.cif DELETE ATOM O4A 1 "
Traceback (most recent call last):
  File "/Applications/CCP4/ccp4-9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Applications/CCP4/ccp4-9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Applications/CCP4/ccp4-9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/acedrg/__main__.py", line 4, in <module>
    from . import acedrg
  File "/Applications/CCP4/ccp4-9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/acedrg/acedrg.py", line 33, in <module>
    from rdkit      import rdBase
  File "/Applications/CCP4/ccp4-9/coot_py2/lib/python2.7/site-packages/rdkit/__init__.py", line 2, in <module>
    from .rdBase import rdkitVersion as __version__
ImportError: dlopen(/Applications/CCP4/ccp4-9/coot_py2/lib/python2.7/site-packages/rdkit/rdBase.so, 0x0002): tried: '/Applications/CCP4/ccp4-9/lib/rdBase.so' (no such file), '/rdBase.so' (no such file), '/Applications/CCP4/ccp4-9/coot_py2/lib/python2.7/site-packages/rdkit/rdBase.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Applications/CCP4/ccp4-9/coot_py2/lib/python2.7/site-packages/rdkit/rdBase.so' (no such file), '/Applications/CCP4/ccp4-9/coot_py2/lib/python2.7/site-packages/rdkit/rdBase.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))
(info-dialog "WARNING:: acedrg failed.
See acedrg-link-from-coot-LYS-PLP-link-instructions.log")
```

The specified log file is empty:
<img width="522" alt="image" src="https://github.com/user-attachments/assets/af21f66c-20ec-4576-b669-b3e6b60d0dd0" />

How do I fix this?

Cheers
Oli

**Comment by pemsley** [comment]
Hi Oli,
Thanks for the bug report. Hopefully it won't be too difficult to fix. The interface was written with for an early version of Acedrg - it seems things have changed.
For now, the alternative is to use CCP4i2:
https://www.youtube.com/watch?v=p4oTJ0bjD3M
starting at 13:20 or so.

**Comment by pemsley** [comment]
@olibclarke 

I can reproduce this problem.

I am not going to fix it. It is a CCP4 packaging problem.

I will work on the Acedrg link interface in Coot 1.
