### ISSUE TITLE
coot-1 gtk3 installation failed on Ubuntu 22.10

### ISSUE THREAD

**Issue by Adwaith99** [pemsley/coot#77]
Hi @pemsley , 

I was trying to install coot 1 on Ubuntu using the build script (https://raw.githubusercontent.com/pemsley/coot/gtk3/build-it-3-3). However, it just fails when starting to build coot. 

I am attaching the build.log file. [
[build.log](https://github.com/pemsley/coot/files/11152709/build.log)

Is there anything I am doing wrong here?

Thank you
Adwaith

**Comment by pemsley** [comment]
Hello @Adwith99,
You are doing the right thing. It seems that the script is not. The build log for coot though, is not. Normally the problem is with Python/PyGObject. The log files for the components are in a compiler-specific subdirectory in the directory where you can find build.log.

**Comment by Adwaith99** [comment]
Hi @pemsley ,

I tried again recently. It fails they same way. It builds a lot of dependencies. Then it starts building coot and it fails as shown in the attached build.log file. Do you have any suggestions to fix this. 

Thank you
Adwaith

**Comment by WarderSar** [comment]
> [build.log](https://github.com/pemsley/coot/files/11885707/build.log) Hi @pemsley ,
> 
> I tried again recently. It fails they same way. It builds a lot of dependencies. Then it starts building coot and it fails as shown in the attached build.log file. Do you have any suggestions to fix this.
> 
> Thank you Adwaith

Hello.

After bunch of hours of researching I found this in [07c1-ninja.txt](https://github.com/pemsley/coot/files/13333230/07c1-ninja.txt): 

bootstrapping ninja...
warning: A compatible version of re2c (>= 0.11.3) was not found; changes to src/*.in.cc will not affect your build.
wrote build.ninja.
bootstrap complete.  rebuilding...

And this in [07d-gobject-introspection.txt](https://github.com/pemsley/coot/files/13333263/07d-gobject-introspection.txt)

Generating gir/gir-glib with a custom command
FAILED: gir/GLib-2.0.gir
...
Traceback (most recent call last):
  File "/home/wardersar/autobuild/building/wardersar-BBR-WAX9_2023-11-13__T09_15_46/gobject-introspection-1.72.0/build/tools/g-ir-scanner", line 98, in <module>
    from giscanner.scannermain import scanner_main
  File "/home/wardersar/autobuild/building/wardersar-BBR-WAX9_2023-11-13__T09_15_46/gobject-introspection-1.72.0/build/giscanner/scannermain.py", line 35, in <module>
    from giscanner.ast import Include, Namespace
  File "/home/wardersar/autobuild/building/wardersar-BBR-WAX9_2023-11-13__T09_15_46/gobject-introspection-1.72.0/build/giscanner/ast.py", line 29, in <module>
    from .sourcescanner import CTYPE_TYPEDEF, CSYMBOL_TYPE_TYPEDEF
  File "/home/wardersar/autobuild/building/wardersar-BBR-WAX9_2023-11-13__T09_15_46/gobject-introspection-1.72.0/build/giscanner/sourcescanner.py", line 34, in <module>
    from giscanner._giscanner import SourceScanner as CSourceScanner
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
ninja: build stopped: subcommand failed.

Any advice? Please!

**Comment by WarderSar** [comment]
> Hello @Adwith99, You are doing the right thing. The build script for coot though, is not. Normally the problem is with Python/PyGObject. The log files for the components are in a compiler-specific subdirectory in the directory where you can find build.log.

Hello.

After bunch of hours of researching I found this in [07c1-ninja.txt](https://github.com/pemsley/coot/files/13333230/07c1-ninja.txt): 

bootstrapping ninja...
warning: A compatible version of re2c (>= 0.11.3) was not found; changes to src/*.in.cc will not affect your build.
wrote build.ninja.
bootstrap complete.  rebuilding...

And this in [07d-gobject-introspection.txt](https://github.com/pemsley/coot/files/13333263/07d-gobject-introspection.txt)

Generating gir/gir-glib with a custom command
FAILED: gir/GLib-2.0.gir
...
Traceback (most recent call last):
  File "/home/wardersar/autobuild/building/wardersar-BBR-WAX9_2023-11-13__T09_15_46/gobject-introspection-1.72.0/build/tools/g-ir-scanner", line 98, in <module>
    from giscanner.scannermain import scanner_main
  File "/home/wardersar/autobuild/building/wardersar-BBR-WAX9_2023-11-13__T09_15_46/gobject-introspection-1.72.0/build/giscanner/scannermain.py", line 35, in <module>
    from giscanner.ast import Include, Namespace
  File "/home/wardersar/autobuild/building/wardersar-BBR-WAX9_2023-11-13__T09_15_46/gobject-introspection-1.72.0/build/giscanner/ast.py", line 29, in <module>
    from .sourcescanner import CTYPE_TYPEDEF, CSYMBOL_TYPE_TYPEDEF
  File "/home/wardersar/autobuild/building/wardersar-BBR-WAX9_2023-11-13__T09_15_46/gobject-introspection-1.72.0/build/giscanner/sourcescanner.py", line 34, in <module>
    from giscanner._giscanner import SourceScanner as CSourceScanner
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
ninja: build stopped: subcommand failed.

Any advice? Please!

**Comment by Adwaith99** [comment]
Hi, 

I just wanted to update that I managed to get it to work. I had linux homebrew installed on my computer and it was interfering with installation when it was searching for the gtk3 package as mentioned in https://github.com/Homebrew/brew/issues/13281. Once I removed it, I was able to intsall it sucessfully.
